### ISSUE TITLE
custom_commands_actions no funciona cuando use_commands_as_whitelist es true

### ISSUE THREAD

**Issue by MiguVT** [Ajneb97/EasyCommandBlocker#14]
Como dije, custom_commands_actions no funciona si use_commands_as_whitelist es true, directamente te envia blocked_command_default_actions, tambien intente añadirlo a la whitelist y simplemente se ejecuta como deberia pasar pero no se ejecuta la accion custom, aqui esta mi configuración:
```yml
tab:
  default:
    priority: 0
    commands:
      - "/l"
      - "/login"
      - "/register"
      - "/reg"
      - "/prem"
      - "/premium"
      - "/cracked"
blocked_command_default_actions:
  - "message: &cSolo puedes usar comandos de /premium, /login, /register y /lobby"
use_commands_as_whitelist: true
commands:
  - "/premium"
  - "/l"
  - "/login"
  - "/reg"
  - "/register"
  - "/prem"
  - "/cracked"
custom_commands_actions:
  pl:
    commands:
      - "/pl"
      - "/plugins"
      - "/bukkit:pl"
      - "/bukkit:plugins"
    actions:
      - "message: &9Paper Plugins:"
      - "message: &8 - &aWhyYouSeeIt?"
  ver:
    commands:
      - "/ver"
      - "/version"
      - "/bukkit:version"
      - "/bukkit:ver"
      - "/bukkit:about"
      - "/about"
    actions:
      - "message: &fNot allowed command"
```
