### ISSUE TITLE
Most likely, Velocity doesn't respond to the whitelist parameter.

### ISSUE THREAD

**Issue by JuraRusan** [Ajneb97/EasyCommandBlocker#16]
I'm using the plugin on both Velocity and Paper. But on Velocity, I need to hide commands so that players can't use them.

- Velocity 3.3.0-SNAPSHOT (git-00ed2284-b415)
- [EasyCommandBlocker] Loading server plugin EasyCommandBlocker v1.9.2

Velocity config:
```yml
tab:
  default:
    priority: 0
    commands: 
      - "/ab"
      - "/antibot"
      - "/banannouncer-reload"
      - "/bareload"
      - "/changepass"
      - "/changepassword"
      - "/litebans"
      - "/litebans:litebans"
      - "/lpv"
      - "/luckpermsvelocity"
      - "/nantibot"
      - "/nlogin"
      - "/offline"
      - "/planbungee"
      - "/planp"
      - "/planproxy"
      - "/planvelocity"
blocked_command_default_actions:
  - "message: &#f42f31 Ошибка: &#caeaf5Вы не можете выполнить данную команду или неверный аргумент!"
use_commands_as_whitelist: false
commands:
  - "/ab"
  - "/antibot"
  - "/banannouncer-reload"
  - "/bareload"
  - "/changepass"
  - "/changepassword"
  - "/litebans"
  - "/litebans:litebans"
  - "/lpv"
  - "/luckpermsvelocity"
  - "/nantibot"
  - "/nlogin"
  - "/offline"
  - "/planbungee"
  - "/planp"
  - "/planproxy"
  - "/planvelocity"
custom_commands_actions:
  example:
    commands:
      - "/velocity"
    actions:
      - "message: &#f42f31 Ошибка: &#caeaf5Вы не можете выполнить данную команду или неверный аргумент!"
```
Plugins: litebans, spicord, ban_announcer, cmiv, easycommandblocker, luckperms, mapmodcompanion, miniplaceholders, nantibot, nlogin, papiproxybridge, plan, proxyplayernotify, velocitab, sayanvanish, skinsrestorer, spark, venturechat
![image](https://github.com/user-attachments/assets/562cadab-bbf6-484d-82e4-9362969a88e2)

Paper config:
```yaml
tab:
  default:
    priority: 0
    commands: 
      - "/login"
      - "/log"
      - "/register"
      - "/reg"
      - "/premium"
      - "/menu"
      - "/lay"
      - "/sit"
      - "/crawl"
      - "/lobby"
blocked_command_default_actions:
  - "message: #f42f31 Ошибка: #caeaf5Вы не можете выполнить данную команду или неверный аргумент!"
use_commands_as_whitelist: true
commands:
  - "/login"
  - "/log"
  - "/register"
  - "/reg"
  - "/premium"
  - "/menu"
  - "/lay"
  - "/sit"
  - "/crawl"
  - "/lobby"
custom_commands_actions:
  example:
    commands:
      - "/velocity"
    actions:
      - "message: #f42f31 Ошибка: #caeaf5Вы не можете выполнить данную команду или неверный аргумент!"
```

Regardless of the parameter set, Velocity commands are still visible, while the needed commands are not. It's possible that the whitelist parameter isn't working properly.
The server was rebooted after changing the parameters. The reboot command was not used.

Thank you!
