### ISSUE TITLE
[EXPLOIT] Escaneo de plugins del servidor.

### ISSUE THREAD

**Issue by PistonCube** [Ajneb97/EasyCommandBlocker#22]
**Buenas, encontré un pequeño exploit en ECB.** Usando el cliente hack *FutureClient*, puedo ver la lista de plugins de cualquier servidor que use ECB. No estoy seguro del método exacto que usa, pero probablemente escanee comandos, dinámicas del servidor o algo similar. A pesar de que en el servidor tienen bloqueados comandos como `/plugins`, `/bukkit:plugins`, etc., el exploit sigue funcionando.  

Existe un plugin llamado **AnarchyExploitFixes**, diseñado para corregir exploits comunes en servidores anárquicos como *2b2t* o aquellos sin reglas, y que parece solucionar este problema:  
 https://github.com/xGinko/AnarchyExploitFixes

El módulo relevante es:  

```yaml
prevent-scanning-server-plugins:
    # Evita que clientes hackeados usen ".plugins" para listar los plugins del servidor.
    # Se recomienda usarlo junto con una whitelist de comandos.
    enable: true
```

Activando esta opción, el exploit queda parcheado.
