### ISSUE TITLE
[FATAL] Velocity compatibility

### ISSUE THREAD

**Issue by CKATEPTb** [Ajneb97/EasyCommandBlocker#6]
When I use the command that EasyCommandBlocker is trying to block, I get the following error
[06:23:32 FATAL]: A plugin tried to deny a command with signable component(s). This is not supported. Disconnecting player Username.

Velocity Details:
>[06:26:32 INFO]: Velocity 3.1.2-SNAPSHOT (git-7d77bfb5-b184)
[06:26:32 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[06:26:32 INFO]: velocitypowered.com - GitHub

config.yml:
```yaml
tab:
  default:
    priority: 0
    commands: []
blocked_command_default_actions:
  - "message: &8&l〘&c&nCЕРВЕР&8&l〙&7Команда не найдена или у вас нету доступа для выполнения этой команды."
use_commands_as_whitelist: false
commands:
  - "/velocity"
  - "/server"
  - "/lpv"
custom_commands_actions:
  example:
    commands: []
    actions: []
```
